name: Build binaries-single

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:

      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"

      - name: Checkout builder
        uses: actions/checkout@v1

      - name: Install arm toolchain
        run: ./scripts/install_arm.sh

      - name: Install ESP-IDF toolchain
        run: ./scripts/install_espidf.sh

      - name: Checkout ulab/micropython
        run: ./scripts/init.sh

      - name: Create artifacts directory
        run: mkdir ./artifacts


      - name: Compile for ESP32 S3
        if: always()
        run: ./scripts/esp32/generic-s3.sh
        
      - name: Merge Artifacts
        uses: actions/upload-artifact/merge@v4
        with:
          name: ${{ inputs.archive_name }}
          pattern: artifact-*
          delete-merged: true

          files: ./artifacts/*
